---
title: "notes_djoralivmodul"
author: "Birgitta"
date: "19/05/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Github

Arbeitt verður á nýggjari "menningar" branch á Github, tá arbeiði er góðkent av Umhvørvisstovuni verða nýggja og gamla branch'inar samantvunnar. Hetta merkir at øll arbeiðsmannagongdin verður dokumentera og goymd til evt. seinni nýtslu.

## Spurningar (tað eru eisini nakrir í TODO listanum)

+ talvurnar
  - hvussu nógvar kanningar skulu verða í listanum? - síðsta kanning, men um talan kann gerðast interactiv er betri!
  - skulu djór, sum eru á svartalistanum vísast? - JA, men skulu bólkast fyri seg

+ Tal av djórasløgum
  - hvat telur við? hvussu langt upp í trænum??

+ Sensitivitets virðir
  - tá man nýtir "ancestor" til at matcha við, skal man so eisini uppdaterað tal av djórasløgum so tað samsvarar við matchaða listan???

## TODO:

+ plotta positiónir
  - bara fyri aliøki? ella fyri fjørðin?
      + trupulleikar við gomlum aliøkum
      + trupulleikar tá alifirðirnir eru defineraðir tvørtur um oyggjar
      + sumi aliøka hava felags samanberingarstøð
      
  - ynski:
      + alifjørðin fyrst
      + so fokus á  aliøki
    
  - interactivt?

+ rokna index virðir
  - dupultkannað við benthos r pakka
  
+ plotta index
  - scatterplots
  - distance til ringsýni ?


## DONE:
+ rmd skal kunna koyra uttan rakstrartøl!
+ hevur Umhvørvisstovan tikið avgerð um open source?
    - vátta at tað verður open source
+ talva við yvirliti (metadata) av djóralívssýnunum
+ inkorpurerað svartalistan - norsk vegleiðing 2016
+ norsku sensitivitets virðini -- leggjast inn sum csv ella út á databasan?? - Databasan er betri.
    - liggur sum csv fílur í projectinum
+ skriva funktiónir til index
+ rokna index virðir
  - dupultkannað við python roknaði indeksir
+ plotta index
  - kort